// Emits the declaration-only type tree the converter reads prop contracts from,
// plus the stub package.json that makes it findable.
//
// Why the stub is load-bearing: the converter's `loadDts` walks up from the
// types root looking for the nearest package.json **with a `name` field**.
// concall-alpha/package.json has none (it is a private Next.js app), so without
// a named package.json at dist/ the walk runs to the filesystem root and the
// build dies with `ENOENT: /package.json`. Generating it here rather than
// committing it keeps a fresh clone working — dist/ is gitignored.
//
// Run from the concall-alpha package root.
import { execFileSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";

rmSync("dist/types", { recursive: true, force: true });
execFileSync("npx", ["tsc", "-p", ".design-sync/tsconfig.dts.json"], { stdio: "inherit" });

mkdirSync("dist", { recursive: true });
writeFileSync(
  "dist/package.json",
  JSON.stringify(
    {
      name: "concall-alpha",
      version: "0.0.0",
      private: true,
      types: "types/.design-sync/ds-entry.d.ts",
      comment:
        "Generated by .design-sync/build-types.mjs for /design-sync. Declaration-only output; not consumed by the Next.js app.",
    },
    null,
    2,
  ) + "\n",
);
console.error("  dist/types + dist/package.json written");
